#!/usr/bin/env bash

set -o errexit -o pipefail

export AWS_ACCESS_KEY_ID=$(curl ${TC_SECRET_URL} | python3 -c 'import json, sys; a = json.load(sys.stdin); print(a["secret"]["aws_access_key"])')
export AWS_SECRET_ACCESS_KEY=$(curl ${TC_SECRET_URL} | python3 -c 'import json, sys; a = json.load(sys.stdin); print(a["secret"]["aws_secret_key"])')


aws s3 sync \
    --metadata "{
    \"Strict-Transport-Security\": \"max-age=31536000\"
}" \
    --metadata-directive "REPLACE" \
    --cache-control "max-age=300" \
    ./public/ "s3://${WEBSITE_BUCKET}/"

